'use server';
/**
 * @fileOverview This file implements a Genkit flow for generating structured content
 * using a 4-agent pipeline based on a user-provided topic.
 *
 * - generateContentFromTopic - A function that orchestrates the content generation process.
 * - GenerateContentFromTopicInput - The input type for the generateContentFromTopic function.
 * - GenerateContentFromTopicOutput - The return type for the generateContentFromTopic function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

// Input Schema
const GenerateContentFromTopicInputSchema = z.object({
  topic: z.string().describe('The main topic for content generation.'),
  sessionId: z.string().describe('The ID of the current session for memory recall.'),
  historicalMessages: z.array(z.object({
    role: z.enum(['user', 'assistant']),
    content: z.string(),
  })).optional().describe('Historical conversation messages to maintain context for follow-up commands.'),
});
export type GenerateContentFromTopicInput = z.infer<typeof GenerateContentFromTopicInputSchema>;

// Output Schema
const GenerateContentFromTopicOutputSchema = z.object({
  finalContent: z.string().describe('The final structured content generated by the agent pipeline.'),
});
export type GenerateContentFromTopicOutput = z.infer<typeof GenerateContentFromTopicOutputSchema>;

// Helper to format historical messages for prompts
function formatHistoricalMessages(messages: GenerateContentFromTopicInput['historicalMessages']): string {
  if (!messages || messages.length === 0) {
    return '';
  }
  return 'Previous conversation context:\n' + messages.map(msg => `${msg.role}: ${msg.content}`).join('\n');
}

// --- Agent Prompts ---

// Agent 1: News Collector
const newsCollectorPrompt = ai.definePrompt({
  name: 'newsCollectorPrompt',
  input: {
    schema: GenerateContentFromTopicInputSchema.extend({
      formattedHistoricalMessages: z.string().optional(),
    }),
  },
  output: {
    schema: z.string().describe('Curated baseline information about the topic.'),
  },
  prompt: `{{{formattedHistoricalMessages}}}

Your role is the News Collector. Your task is to curate comprehensive baseline information about the given topic. Focus on key facts, recent developments, and relevant background.
Topic: {{{topic}}}

Provide the curated information in a detailed, factual manner.`,
});

// Agent 2: Summarizer
const summarizerPrompt = ai.definePrompt({
  name: 'summarizerPrompt',
  input: {
    schema: z.object({
      newsCollectorOutput: z.string().describe('The baseline information from the News Collector.'),
      topic: z.string().describe('The original topic.'),
      formattedHistoricalMessages: z.string().optional(),
    }),
  },
  output: {
    schema: z.string().describe('Extracted critical data points and condensed summary.'),
  },
  prompt: `{{{formattedHistoricalMessages}}}

Your role is the Summarizer. Your task is to extract critical data points and condense the provided baseline information into a concise summary. Identify the most important facts and insights related to the original topic.
Original Topic: {{{topic}}}
Baseline Information:
{{{newsCollectorOutput}}}

Provide a clear and concise summary with key data points.`,
});

// Agent 3: Content Writer
const contentWriterPrompt = ai.definePrompt({
  name: 'contentWriterPrompt',
  input: {
    schema: z.object({
      summarizerOutput: z.string().describe('The condensed summary and critical data points from the Summarizer.'),
      topic: z.string().describe('The original topic.'),
      formattedHistoricalMessages: z.string().optional(),
    }),
  },
  output: {
    schema: z.string().describe('Full-length structured content draft.'),
  },
  prompt: `{{{formattedHistoricalMessages}}}

Your role is the Content Writer. Your task is to draft a full-length, structured piece of content based on the provided summary and critical data points. Ensure the content is coherent, engaging, and well-organized. Use headings, paragraphs, and bullet points as appropriate.
Original Topic: {{{topic}}}
Summary & Key Data Points:
{{{summarizerOutput}}}

Draft the full content piece.`,
});

// Agent 4: Editor
const editorPrompt = ai.definePrompt({
  name: 'editorPrompt',
  input: {
    schema: z.object({
      contentWriterOutput: z.string().describe('The draft content from the Content Writer.'),
      topic: z.string().describe('The original topic.'),
      formattedHistoricalMessages: z.string().optional(),
    }),
  },
  output: {
    schema: z.string().describe('Final refined and formatted content.'),
  },
  prompt: `{{{formattedHistoricalMessages}}}

Your role is the Editor. Your task is to refine the provided content draft. Check for grammar, spelling, clarity, and coherence. Ensure the content meets standard formatting guidelines, addresses the original topic effectively, and is ready for publication. If there are any specific constraints mentioned in the historical messages, apply them.
Original Topic: {{{topic}}}
Content Draft:
{{{contentWriterOutput}}}

Provide the finalized, polished content.`,
});


// --- Genkit Flow ---

const generateContentFromTopicFlow = ai.defineFlow(
  {
    name: 'generateContentFromTopicFlow',
    inputSchema: GenerateContentFromTopicInputSchema,
    outputSchema: GenerateContentFromTopicOutputSchema,
  },
  async (input) => {
    const formattedHistoricalMessages = formatHistoricalMessages(input.historicalMessages);

    // Agent 1: News Collector
    const newsCollectorResponse = await newsCollectorPrompt({
      topic: input.topic,
      formattedHistoricalMessages,
      sessionId: input.sessionId, 
      historicalMessages: input.historicalMessages,
    });
    const newsCollectorOutput = newsCollectorResponse.output!;

    // Agent 2: Summarizer
    const summarizerResponse = await summarizerPrompt({
      newsCollectorOutput,
      topic: input.topic,
      formattedHistoricalMessages,
    });
    const summarizerOutput = summarizerResponse.output!;

    // Agent 3: Content Writer
    const contentWriterResponse = await contentWriterPrompt({
      summarizerOutput,
      topic: input.topic,
      formattedHistoricalMessages,
    });
    const contentWriterOutput = contentWriterResponse.output!;

    // Agent 4: Editor
    const editorResponse = await editorPrompt({
      contentWriterOutput,
      topic: input.topic,
      formattedHistoricalMessages,
    });
    const finalContent = editorResponse.output!;

    return { finalContent };
  }
);

// Wrapper function for external calls
export async function generateContentFromTopic(
  input: GenerateContentFromTopicInput
): Promise<GenerateContentFromTopicOutput> {
  return generateContentFromTopicFlow(input);
}
